"""Shared constants for the Rhemata backend."""

# Bible book name -> 3-letter abbreviation mapping.
#
# This is the canonical source for book-name recognition across the whole
# product. frontend/app/study/page.tsx, frontend/app/library/page.tsx, and
# (for the code<->full-name identity only) frontend/lib/study-reference.ts
# no longer hand-type their own copies of this or ABBREV_TO_NAME below —
# they import frontend/lib/generated/book-maps.ts, generated from this file
# by scripts/generate_book_maps_ts.py. Edit BOOK_MAP/ABBREV_TO_NAME here,
# then run `python3.12 scripts/generate_book_maps_ts.py` to regenerate;
# `python3.12 scripts/generate_book_maps_ts.py --check` fails if the
# generated file has drifted. See CLAUDE.md Landmines, "The book-name map
# exists as five independent hand-maintained copies."
BOOK_MAP = {
    # Old Testament
    "genesis": "GEN", "gen": "GEN",
    "exodus": "EXO", "exo": "EXO", "exod": "EXO",
    "leviticus": "LEV", "lev": "LEV",
    "numbers": "NUM", "num": "NUM",
    "deuteronomy": "DEU", "deut": "DEU", "deu": "DEU",
    "joshua": "JOS", "josh": "JOS", "jos": "JOS",
    "judges": "JDG", "judg": "JDG", "jdg": "JDG",
    "ruth": "RUT", "rut": "RUT",
    "1 samuel": "1SA", "1samuel": "1SA", "1 sam": "1SA", "1sam": "1SA", "1sa": "1SA",
    "first samuel": "1SA", "i samuel": "1SA",
    "2 samuel": "2SA", "2samuel": "2SA", "2 sam": "2SA", "2sam": "2SA", "2sa": "2SA",
    "second samuel": "2SA", "ii samuel": "2SA",
    "1 kings": "1KI", "1kings": "1KI", "1 kgs": "1KI", "1kgs": "1KI", "1ki": "1KI",
    "first kings": "1KI", "i kings": "1KI",
    "2 kings": "2KI", "2kings": "2KI", "2 kgs": "2KI", "2kgs": "2KI", "2ki": "2KI",
    "second kings": "2KI", "ii kings": "2KI",
    "1 chronicles": "1CH", "1chronicles": "1CH", "1 chr": "1CH", "1chr": "1CH", "1ch": "1CH",
    "first chronicles": "1CH", "i chronicles": "1CH",
    "2 chronicles": "2CH", "2chronicles": "2CH", "2 chr": "2CH", "2chr": "2CH", "2ch": "2CH",
    "second chronicles": "2CH", "ii chronicles": "2CH",
    "ezra": "EZR", "ezr": "EZR",
    "nehemiah": "NEH", "neh": "NEH",
    "esther": "EST", "esth": "EST", "est": "EST",
    "job": "JOB",
    "psalms": "PSA", "psalm": "PSA", "psa": "PSA", "ps": "PSA",
    "proverbs": "PRO", "prov": "PRO", "pro": "PRO",
    "ecclesiastes": "ECC", "eccl": "ECC", "ecc": "ECC",
    "song of solomon": "SNG", "song of songs": "SNG", "song": "SNG", "sng": "SNG", "sos": "SNG",
    "isaiah": "ISA", "isa": "ISA",
    "jeremiah": "JER", "jer": "JER",
    "lamentations": "LAM", "lam": "LAM",
    "ezekiel": "EZK", "ezek": "EZK", "ezk": "EZK",
    "daniel": "DAN", "dan": "DAN",
    "hosea": "HOS", "hos": "HOS",
    "joel": "JOL", "jol": "JOL",
    "amos": "AMO", "amo": "AMO",
    "obadiah": "OBA", "obad": "OBA", "oba": "OBA",
    "jonah": "JON", "jon": "JON",
    "micah": "MIC", "mic": "MIC",
    "nahum": "NAM", "nah": "NAM", "nam": "NAM",
    "habakkuk": "HAB", "hab": "HAB",
    "zephaniah": "ZEP", "zeph": "ZEP", "zep": "ZEP",
    "haggai": "HAG", "hag": "HAG",
    "zechariah": "ZEC", "zech": "ZEC", "zec": "ZEC",
    "malachi": "MAL", "mal": "MAL",
    # New Testament
    "matthew": "MAT", "matt": "MAT", "mat": "MAT",
    "mark": "MRK", "mrk": "MRK",
    "luke": "LUK", "luk": "LUK",
    "john": "JHN", "jhn": "JHN",
    "acts": "ACT", "act": "ACT",
    "romans": "ROM", "rom": "ROM",
    "1 corinthians": "1CO", "1corinthians": "1CO", "1 cor": "1CO", "1cor": "1CO", "1co": "1CO",
    "first corinthians": "1CO", "i corinthians": "1CO",
    "2 corinthians": "2CO", "2corinthians": "2CO", "2 cor": "2CO", "2cor": "2CO", "2co": "2CO",
    "second corinthians": "2CO", "ii corinthians": "2CO",
    "galatians": "GAL", "gal": "GAL",
    "ephesians": "EPH", "eph": "EPH",
    "philippians": "PHP", "phil": "PHP", "php": "PHP",
    "colossians": "COL", "col": "COL",
    "1 thessalonians": "1TH", "1thessalonians": "1TH", "1 thess": "1TH", "1thess": "1TH", "1th": "1TH",
    "first thessalonians": "1TH", "i thessalonians": "1TH",
    "2 thessalonians": "2TH", "2thessalonians": "2TH", "2 thess": "2TH", "2thess": "2TH", "2th": "2TH",
    "second thessalonians": "2TH", "ii thessalonians": "2TH",
    "1 timothy": "1TI", "1timothy": "1TI", "1 tim": "1TI", "1tim": "1TI", "1ti": "1TI",
    "first timothy": "1TI", "i timothy": "1TI",
    "2 timothy": "2TI", "2timothy": "2TI", "2 tim": "2TI", "2tim": "2TI", "2ti": "2TI",
    "second timothy": "2TI", "ii timothy": "2TI",
    "titus": "TIT", "tit": "TIT",
    "philemon": "PHM", "phlm": "PHM", "phm": "PHM",
    "hebrews": "HEB", "heb": "HEB",
    "james": "JAS", "jas": "JAS",
    "1 peter": "1PE", "1peter": "1PE", "1 pet": "1PE", "1pet": "1PE", "1pe": "1PE",
    "first peter": "1PE", "i peter": "1PE",
    "2 peter": "2PE", "2peter": "2PE", "2 pet": "2PE", "2pet": "2PE", "2pe": "2PE",
    "second peter": "2PE", "ii peter": "2PE",
    "1 john": "1JN", "1john": "1JN", "1 jn": "1JN", "1jn": "1JN",
    "first john": "1JN", "i john": "1JN",
    "2 john": "2JN", "2john": "2JN", "2 jn": "2JN", "2jn": "2JN",
    "second john": "2JN", "ii john": "2JN",
    "3 john": "3JN", "3john": "3JN", "3 jn": "3JN", "3jn": "3JN",
    "third john": "3JN", "iii john": "3JN",
    "jude": "JUD", "jud": "JUD",
    "revelation": "REV", "rev": "REV",
}

# Reverse mapping: abbreviation -> canonical book name
ABBREV_TO_NAME = {
    "GEN": "Genesis", "EXO": "Exodus", "LEV": "Leviticus", "NUM": "Numbers",
    "DEU": "Deuteronomy", "JOS": "Joshua", "JDG": "Judges", "RUT": "Ruth",
    "1SA": "1 Samuel", "2SA": "2 Samuel", "1KI": "1 Kings", "2KI": "2 Kings",
    "1CH": "1 Chronicles", "2CH": "2 Chronicles", "EZR": "Ezra", "NEH": "Nehemiah",
    "EST": "Esther", "JOB": "Job", "PSA": "Psalms", "PRO": "Proverbs",
    "ECC": "Ecclesiastes", "SNG": "Song of Solomon", "ISA": "Isaiah", "JER": "Jeremiah",
    "LAM": "Lamentations", "EZK": "Ezekiel", "DAN": "Daniel", "HOS": "Hosea",
    "JOL": "Joel", "AMO": "Amos", "OBA": "Obadiah", "JON": "Jonah",
    "MIC": "Micah", "NAM": "Nahum", "HAB": "Habakkuk", "ZEP": "Zephaniah",
    "HAG": "Haggai", "ZEC": "Zechariah", "MAL": "Malachi",
    "MAT": "Matthew", "MRK": "Mark", "LUK": "Luke", "JHN": "John",
    "ACT": "Acts", "ROM": "Romans", "1CO": "1 Corinthians", "2CO": "2 Corinthians",
    "GAL": "Galatians", "EPH": "Ephesians", "PHP": "Philippians", "COL": "Colossians",
    "1TH": "1 Thessalonians", "2TH": "2 Thessalonians", "1TI": "1 Timothy",
    "2TI": "2 Timothy", "TIT": "Titus", "PHM": "Philemon", "HEB": "Hebrews",
    "JAS": "James", "1PE": "1 Peter", "2PE": "2 Peter", "1JN": "1 John",
    "2JN": "2 John", "3JN": "3 John", "JUD": "Jude", "REV": "Revelation",
}

# ── Topic taxonomy (257 tags, 15 categories) ─────────────────────────────────
# Keep in sync with scripts/taxonomy.py and taxonomy.md.

VALID_TAGS = {
    # 1. Holy Spirit & Spiritual Gifts
    "Baptism in the Holy Spirit", "Speaking in Tongues", "Private Prayer Language",
    "Gifts of the Spirit", "Prophecy", "Word of Knowledge", "Word of Wisdom",
    "Discerning of Spirits", "Gifts of Healing", "Working of Miracles",
    "Gift of Faith", "Interpretation of Tongues", "Cessationism vs Continuationism",
    "Anointing", "Signs and Wonders", "Manifestations of the Spirit",
    "Prophetic Dreams and Visions", "Spiritual Impartation", "Laying on of Hands",
    "Spirit-Filled Life", "Activating Spiritual Gifts", "Quenching the Spirit",
    "Yielding to the Holy Spirit", "Fruit of the Spirit", "Spirit and Word Balance",
    "Character Before Gift", "Charismatic Theology",
    # 2. Spiritual Warfare & Deliverance
    "Deliverance Ministry", "Spiritual Warfare", "Expelling Demons", "Demonology",
    "Strongholds in the Mind", "Binding and Loosing", "Territorial Spirits",
    "Principalities and Powers", "Weapons of Our Warfare", "Armor of God",
    "Generational Curses", "Breaking Bloodline Curses", "Jezebel Spirit",
    # 3. Prayer, Intercession & the Prophetic
    "Intercessory Prayer", "Intercession", "Prophetic Intercession",
    "Fasting and Prayer", "Discerning Times and Seasons", "Hearing God's Voice",
    "Hearing God", "Power of Prayer", "Waiting on God", "Seeking God",
    "Personal Prophecy", "Testing Prophecy", "Judging Prophecy",
    "Accountability in Prophecy", "Pitfalls of the Prophetic", "Dreams and Visions",
    "Discerning God's Voice", "God's Will and Guidance",
    # 4. Inner Healing & Identity
    "Inner Healing", "Overcoming Rejection", "Overcoming the Orphan Spirit",
    "Spirit of Adoption", "Spiritual Sonship", "Identity in Christ",
    "Renewing the Mind", "Freedom from Intimidation", "Overcoming Offense",
    "Healing Severe Trauma", "Finding Purpose in Pain", "Emotional Healing",
    "Mental Health and Faith", "Freedom in Christ", "Brokenness",
    "Abiding in Christ", "Suffering as Sanctification", "Dying to Self",
    "Taking Up Your Cross", "Spirit Soul and Body",
    # 5. Presence, Worship & Encounter
    "Worship in Spirit and Truth", "Deep Intimacy with God", "Spiritual Hunger",
    "Encounter with God", "Revival Culture", "Intimacy with God", "Knowing God",
    "God's Presence", "Revival", "Worship",
    # 6. Fivefold Ministry
    "Fivefold Ministry", "Ephesians 4 Leadership", "Equipping the Saints",
    "Recognizing Your Ministry Gift", "Apostolic Ministry", "Apostolic Authority",
    "Apostolic Networks", "Pioneering Ministry", "Office of the Prophet",
    "Evangelism", "Gift of the Evangelist", "Power Evangelism", "Street Evangelism",
    "Soul Winning", "Great Commission", "Pastoral Ministry",
    "Shepherding the Flock", "Pastoral Care", "Spiritual Fathers and Mothers",
    "Teaching Ministry", "Biblical Exposition", "Rightly Handling Scripture",
    "Accountability in Ministry", "Character in Leadership", "Humility in Ministry",
    "Women in Ministry",
    # 7. Kingdom, Theology & Mission
    "Kingdom of God", "Gospel", "Salvation", "Repentance", "Grace", "Atonement",
    "Resurrection", "New Creation", "Second Coming", "End Times", "Eschatology",
    "Israel and the Church", "Israel in Bible Prophecy", "Jewish Roots of Christianity",
    "Trinitarian Theology", "Word of God", "New Covenant", "Redemption",
    "Justification", "The Cross", "Holiness", "Sanctification",
    "Theology of the Holy Spirit",
    # 8. Leadership & Church Culture
    "Culture of Honor", "Spiritual Covering", "Delegated Authority",
    "Accountability and Mentorship", "Servant Leadership", "Leadership Development",
    "Preserving Revival", "Building the Church", "Vision and Mission",
    "Spiritual Discernment about Church", "Spiritual Authority",
    "Unity in the Church", "Unity in the Body of Christ", "Integrity in Leadership",
    "Moral Failure and Restoration", "Healthy Church Culture",
    "Church Governance and Structure",
    # 9. Faith, Finances & Provision
    "Faith", "Biblical Stewardship", "Generous Living", "Tithing and Generosity",
    "Divine Favor", "Supernatural Provision", "Trusting God in Hardship",
    "Contentment", "Faithfulness in Lack", "Seasons of Wilderness",
    "Financial Wisdom", "Faith and Obedience", "Dependence on God", "Trust in God",
    "Obedience", "Perseverance", "Suffering and Trials", "Overcoming Fear",
    "Sanctifying Grace",
    # 10. Purpose, Calling & Destiny
    "Purpose and Calling", "Discovering Your Destiny", "Releasing Your Potential",
    "Recognizing Your Gift", "Calling and Vocation", "Workplace as Ministry",
    # 11. Christian Growth & Discipleship
    "Discipleship", "Spiritual Growth", "Spiritual Maturity", "Character Formation",
    "Humility", "Surrender", "Lordship of Christ", "Walking in the Spirit",
    "Overcoming Sin", "Overcoming Temptation", "Transformation", "Spiritual Disciplines",
    "Testimony",
    # 12. Family, Purity & Relationships
    "Marriage", "Parenting", "Fatherhood", "Motherhood", "Raising Godly Children",
    "Generational Blessing", "Family Prayer", "Forgiveness and Reconciliation",
    "Purity and Sexuality", "Dating and Relationships", "Singleness",
    "Covenant Marriage", "Community and Fellowship", "Friendship",
    "Sexual Integrity", "Submission in Marriage",
    # 13. Divine Healing & Wholeness
    "Divine Healing", "Physical Healing", "Healing Ministry", "Healing Evangelism",
    "Faith for Healing", "Healing in the Atonement", "Miracles",
    "Supernatural Healing", "Healing and Suffering", "Healing Testimony",
    "When Healing Doesn't Come", "Suffering and Sovereignty", "Theology of Healing",
    "Unanswered Prayer", "Trusting God Through Illness",
    # 14. Biblical Studies & Theology
    "Biblical Hermeneutics", "Interpreting Scripture", "How to Study the Bible",
    "Methods of Bible Study", "Biblical Typology and Symbolism", "Tabernacle of Moses",
    "Feasts of Israel", "Temple and Priesthood", "Foundations of Christian Doctrine",
    "Water Baptism", "Doctrine of the Church", "Scripture and Authority",
    "Law and Grace", "Restoration Theology",
    # 15. Church History & Revival
    "Church History", "History of Revival", "Azusa Street Revival", "Welsh Revival",
    "First Great Awakening", "Second Great Awakening", "Pentecostal History",
    "Charismatic Renewal", "Historical Revivals", "Conditions for Revival",
    "Prayer and Revival", "John Wesley and Methodism", "Charles Finney",
    "Evan Roberts", "William Seymour", "Smith Wigglesworth", "Kathryn Kuhlman",
    "Desert Fathers", "Early Church", "Church Fathers",
}

TAXONOMY_LIST = ", ".join(sorted(VALID_TAGS))
