#!/usr/bin/env python3
"""
apply_migration_084.py -- Apply and verify migration 084
(read-only corpus-analysis role: rhemata_readonly_analysis).

Idempotent: role/grant/policy creation is guarded (role via DO-block
existence check, policies via DROP POLICY IF EXISTS before CREATE).
Generates a fresh password every run and writes it to
backend/app/.env.readonly-analysis (chmod 600) -- never printed to stdout,
never embedded in the migration SQL file itself.

Verification runs on FRESH connections (migration 049 landmine, Invariant 9):
  1. new role can SELECT a corpus table (documents)
  2. new role's write attempt on a corpus table is REJECTED
  3. new role's read attempt on a user/auth table is REJECTED (public.user_roles
     and auth.users -- two independent checks)
  4. the existing read-write connection (SUPABASE_DB_URL / postgres role) is
     unchanged and still works

Usage:
  python3 scripts/apply_migration_084.py
"""
import os
import secrets
import stat
import sys
from pathlib import Path
from urllib.parse import unquote, urlparse

from dotenv import load_dotenv

ROOT = Path(__file__).resolve().parent.parent
load_dotenv(ROOT / "backend" / "app" / ".env")

ROLE_NAME = "rhemata_readonly_analysis"
READONLY_ENV_PATH = ROOT / "backend" / "app" / ".env.readonly-analysis"

_pass = 0
_fail = 0


def check(label, passed, detail=None):
    global _pass, _fail
    tag = "PASS" if passed else "FAIL"
    print("  [%s] %s" % (tag, label))
    if detail:
        print("         %s" % detail)
    if passed:
        _pass += 1
    else:
        _fail += 1


def get_admin_conn():
    import psycopg2

    db_url = os.environ["SUPABASE_DB_URL"]
    p = urlparse(db_url)
    return psycopg2.connect(
        host=p.hostname,
        port=p.port or 5432,
        user=unquote(p.username or ""),
        password=unquote(p.password or ""),
        dbname=p.path.lstrip("/"),
    )


def get_readonly_conn():
    import psycopg2

    p = urlparse(os.environ["SUPABASE_DB_URL"])
    host = p.hostname
    port = p.port or 5432
    admin_user = unquote(p.username or "")
    # Supavisor pooler usernames are "<role>.<project-ref>"; mirror the
    # project-ref suffix from the existing admin connection's username.
    if "." in admin_user:
        project_ref = admin_user.split(".", 1)[1]
        ro_user = "%s.%s" % (ROLE_NAME, project_ref)
    else:
        ro_user = ROLE_NAME
    password = _read_readonly_password()
    return psycopg2.connect(
        host=host,
        port=port,
        user=ro_user,
        password=password,
        dbname=p.path.lstrip("/"),
    )


def _read_readonly_password():
    for line in READONLY_ENV_PATH.read_text().splitlines():
        if line.startswith("READONLY_ANALYSIS_DB_URL="):
            url = line.split("=", 1)[1]
            return unquote(urlparse(url).password or "")
    raise RuntimeError("READONLY_ANALYSIS_DB_URL not found in %s" % READONLY_ENV_PATH)


def _role_exists(cur):
    cur.execute("SELECT 1 FROM pg_roles WHERE rolname = %s", (ROLE_NAME,))
    return cur.fetchone() is not None


def apply_migration(conn):
    cur = conn.cursor()
    migration_sql = (ROOT / "migrations" / "084_readonly_analysis_role.sql").read_text()
    cur.execute(migration_sql)
    conn.commit()
    print("Migration 084 applied OK (role, grants, policies)")
    cur.close()


def set_password_and_store_conn_string(admin_conn):
    import psycopg2.sql as sql

    password = secrets.token_urlsafe(24)

    cur = admin_conn.cursor()
    cur.execute(
        sql.SQL("ALTER ROLE {} WITH PASSWORD {}").format(
            sql.Identifier(ROLE_NAME), sql.Literal(password)
        )
    )
    admin_conn.commit()
    cur.close()

    p = urlparse(os.environ["SUPABASE_DB_URL"])
    admin_user = unquote(p.username or "")
    if "." in admin_user:
        project_ref = admin_user.split(".", 1)[1]
        ro_user = "%s.%s" % (ROLE_NAME, project_ref)
    else:
        ro_user = ROLE_NAME

    conn_string = "postgresql://%s:%s@%s:%s/%s" % (
        ro_user,
        password,
        p.hostname,
        p.port or 5432,
        p.path.lstrip("/"),
    )

    contents = (
        "# READ-ONLY corpus-analysis database credentials.\n"
        "# Generated by scripts/apply_migration_084.py (migration 084).\n"
        "#\n"
        "# This role (%s) can SELECT the corpus tables listed in\n"
        "# migrations/084_readonly_analysis_role.sql and NOTHING else -- it\n"
        "# cannot INSERT/UPDATE/DELETE/DDL anywhere, and it cannot read any\n"
        "# user/auth/metering table. Point overnight analysis jobs (Grok,\n"
        "# Qwen, etc.) at READONLY_ANALYSIS_DB_URL below.\n"
        "#\n"
        "# DO NOT confuse this with backend/app/.env's SUPABASE_DB_URL, which\n"
        "# is the full read-write application connection.\n"
        "READONLY_ANALYSIS_DB_URL=%s\n" % (ROLE_NAME, conn_string)
    )
    READONLY_ENV_PATH.write_text(contents)
    READONLY_ENV_PATH.chmod(stat.S_IRUSR | stat.S_IWUSR)  # chmod 600
    print("Wrote %s (chmod 600), password redacted here." % READONLY_ENV_PATH)


def main():
    print("\nread-only corpus-analysis role -- migration 084 apply + verify")
    print("=" * 68)

    admin_conn = get_admin_conn()
    cur = admin_conn.cursor()
    role_already_existed = _role_exists(cur)
    cur.close()

    apply_migration(admin_conn)
    set_password_and_store_conn_string(admin_conn)
    admin_conn.close()

    print()
    print("Verification (fresh connections):")

    # 1. new role can read a corpus table
    try:
        ro_conn = get_readonly_conn()
        ro_conn.autocommit = True
        ro_cur = ro_conn.cursor()
        ro_cur.execute("SELECT count(*) FROM documents;")
        n = ro_cur.fetchone()[0]
        check("readonly role: SELECT count(*) FROM documents", True, "%d rows visible" % n)
        ro_cur.execute("SELECT count(*) FROM propositions;")
        n2 = ro_cur.fetchone()[0]
        check("readonly role: SELECT count(*) FROM propositions", True, "%d rows visible" % n2)
    except Exception as e:
        check("readonly role: SELECT count(*) FROM documents", False, "%r" % e)
        ro_conn = None

    # 2. new role's write attempt is rejected
    if ro_conn is not None:
        try:
            ro_cur.execute("DELETE FROM documents WHERE false;")
            check("readonly role: DELETE FROM documents WHERE false REJECTED", False,
                  "write unexpectedly SUCCEEDED")
        except Exception as e:
            check("readonly role: DELETE FROM documents WHERE false REJECTED", True, "%r" % e)

        try:
            ro_cur.execute("INSERT INTO sources DEFAULT VALUES;")
            check("readonly role: INSERT INTO sources REJECTED", False,
                  "write unexpectedly SUCCEEDED")
        except Exception as e:
            check("readonly role: INSERT INTO sources REJECTED", True, "%r" % e)

        # 3. new role's read attempt on user/auth tables is rejected
        try:
            ro_cur.execute("SELECT * FROM user_roles LIMIT 1;")
            check("readonly role: SELECT FROM public.user_roles REJECTED", False,
                  "read unexpectedly SUCCEEDED")
        except Exception as e:
            check("readonly role: SELECT FROM public.user_roles REJECTED", True, "%r" % e)

        try:
            ro_cur.execute("SELECT * FROM auth.users LIMIT 1;")
            check("readonly role: SELECT FROM auth.users REJECTED", False,
                  "read unexpectedly SUCCEEDED")
        except Exception as e:
            check("readonly role: SELECT FROM auth.users REJECTED", True, "%r" % e)

        ro_cur.close()
        ro_conn.close()

    # 4. existing read-write connection unchanged and still works
    try:
        main_conn = get_admin_conn()
        main_cur = main_conn.cursor()
        main_cur.execute("SELECT current_user;")
        u = main_cur.fetchone()[0]
        main_cur.execute("SELECT count(*) FROM documents;")
        n = main_cur.fetchone()[0]
        check(
            "existing read-write connection (SUPABASE_DB_URL) still works",
            u == "postgres",
            "current_user=%s, documents visible=%d" % (u, n),
        )
        main_cur.close()
        main_conn.close()
    except Exception as e:
        check("existing read-write connection (SUPABASE_DB_URL) still works", False, "%r" % e)

    print()
    print("Role pre-existed before this run: %s" % role_already_existed)
    print("%d/%d checks passed" % (_pass, _pass + _fail))
    if _fail:
        sys.exit(1)


if __name__ == "__main__":
    main()
